//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ljdf.CommandLine {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ljdf.CommandLine.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 特性”{0}“只能应用于”{1}“类型的属性。 的本地化字符串。
        /// </summary>
        internal static string AttrMustApplyToPropOfType {
            get {
                return ResourceManager.GetString("AttrMustApplyToPropOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法将“{0}”类型的值赋给“{1}”类型的“{2}”属性，该属性位于类型”{3}“中。 的本地化字符串。
        /// </summary>
        internal static string CannotAssignTo {
            get {
                return ResourceManager.GetString("CannotAssignTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法将值“{0}”转换成“{1}”类型的对象。 的本地化字符串。
        /// </summary>
        internal static string CannotConvertFrom {
            get {
                return ResourceManager.GetString("CannotConvertFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重复添加处理程序：“{0}”。 的本地化字符串。
        /// </summary>
        internal static string HandlerDuplicated {
            get {
                return ResourceManager.GetString("HandlerDuplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 处理程序“{0}”未应用任何“{1}”特性。 的本地化字符串。
        /// </summary>
        internal static string HandlerLackOfCmdAttr {
            get {
                return ResourceManager.GetString("HandlerLackOfCmdAttr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ： 的本地化字符串。
        /// </summary>
        internal static string Help_Colon {
            get {
                return ResourceManager.GetString("Help_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 , 的本地化字符串。
        /// </summary>
        internal static string Help_Comma {
            get {
                return ResourceManager.GetString("Help_Comma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 简介 的本地化字符串。
        /// </summary>
        internal static string Help_Description {
            get {
                return ResourceManager.GetString("Help_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 命令执行完成。 的本地化字符串。
        /// </summary>
        internal static string Help_Done {
            get {
                return ResourceManager.GetString("Help_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        internal static string Help_Error {
            get {
                return ResourceManager.GetString("Help_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选项 的本地化字符串。
        /// </summary>
        internal static string Help_Option {
            get {
                return ResourceManager.GetString("Help_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可选 的本地化字符串。
        /// </summary>
        internal static string Help_Optional {
            get {
                return ResourceManager.GetString("Help_Optional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认值 的本地化字符串。
        /// </summary>
        internal static string Help_OptionalValue {
            get {
                return ResourceManager.GetString("Help_OptionalValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用 的本地化字符串。
        /// </summary>
        internal static string Help_Usage {
            get {
                return ResourceManager.GetString("Help_Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不合法的命令名称：”{0}“。命令名称至少需要包含 1 个字符，且这些字符只能是字母、数字和连接符(-)，同时第一个字符必须是字母。 的本地化字符串。
        /// </summary>
        internal static string InvalidCommandName {
            get {
                return ResourceManager.GetString("InvalidCommandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不合法的长名称：”{0}“。长名称至少需要包含 2 个字符，且这些字符只能是字母、数字和连接符(-)，同时第一个字符必须是字母。 的本地化字符串。
        /// </summary>
        internal static string InvalidLongName {
            get {
                return ResourceManager.GetString("InvalidLongName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不合法的短名称：”{0}“。短名称只能包含一个字符，且该字符必须是字母。 的本地化字符串。
        /// </summary>
        internal static string InvalidShortName {
            get {
                return ResourceManager.GetString("InvalidShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 特性“{0}”的“{1}”属性的值不能大于“{2}”属性的值。 的本地化字符串。
        /// </summary>
        internal static string MinCannotGtMax {
            get {
                return ResourceManager.GetString("MinCannotGtMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 处理程序”{0}“最多只能有一个默认属性。 的本地化字符串。
        /// </summary>
        internal static string OnlyOneDefaultProp {
            get {
                return ResourceManager.GetString("OnlyOneDefaultProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重复定义选项名称：”{0}“。 的本地化字符串。
        /// </summary>
        internal static string OptionNameDuplicated {
            get {
                return ResourceManager.GetString("OptionNameDuplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打印帮助信息 的本地化字符串。
        /// </summary>
        internal static string PrintHelp {
            get {
                return ResourceManager.GetString("PrintHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打印版本信息 的本地化字符串。
        /// </summary>
        internal static string PrintVersion {
            get {
                return ResourceManager.GetString("PrintVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 特性“{0}”的“{1}”属性的值必须大于等于1。 的本地化字符串。
        /// </summary>
        internal static string PropOfAttrMustEqOrGtOne {
            get {
                return ResourceManager.GetString("PropOfAttrMustEqOrGtOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用“-?”选项查看帮助。 的本地化字符串。
        /// </summary>
        internal static string SeeHelp {
            get {
                return ResourceManager.GetString("SeeHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 短名称与长名称不能都同时为 null。 的本地化字符串。
        /// </summary>
        internal static string ShortNameAndLongNameCannotBeNull {
            get {
                return ResourceManager.GetString("ShortNameAndLongNameCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知的命令或选项。 的本地化字符串。
        /// </summary>
        internal static string UnknownCommandOrOption {
            get {
                return ResourceManager.GetString("UnknownCommandOrOption", resourceCulture);
            }
        }
    }
}
